name: UnpersistMobs
version: ${version}
main: org.nineteam.unpersistMobs.UnpersistMobs
api-version: '1.18'
load: STARTUP
authors: [ Venom Lightning ]
description: Tweak despawning of persistent mobs
commands:
  reload:
    permission: unpersistmobs.reload
  stats:
    permission: unpersistmobs.stats