name: UnpersistMobs
version: '1.2-SNAPSHOT'
main: org.nineteam.unpersistMobs.UnpersistMobs
api-version: '1.19'
load: STARTUP
authors: [ Venom Lightning ]
description: Tweak despawning of persistent mobs
commands:
  reload:
    permission: unpersistmobs.reload
  stats:
    permission: unpersistmobs.stats